apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: todo
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - name: vaultValueType
      value: "map"
    - name: defaultNamespace
      value: "todo"
